name: Update Hugging Face Deployment

on:
  push:
    branches:
      - main

env:
  USER_NAME: "Carlos Escobar"  # Replace with your name
  HF_SPACE: "Broomva/book-broomva-chat"  # Replace with your Hugging Face space name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./chat

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          USER_EMAIL: ${{ env.USER_EMAIL }}  # Assuming you've set your email as a secret
        run: |
          git config --global user.email "${{ env.USER_EMAIL }}"
          git config --global user.name "${{ env.USER_NAME }}"
          cd chat
          git add .
          git commit -m "Update app"
          git push https://${{ secrets.HF_TOKEN }}@huggingface.co/spaces/${{ env.HF_SPACE }} main
